### ISSUE TITLE
new features: exclude command, formmated ~/.emacs.keyfreq

### ISSUE THREAD

**Issue by redguardtoo** [dacap/keyfreq#15]
see https://github.com/redguardtoo/emacs.d/blob/master/site-lisp/keyfreq/keyfreq.el

```changelog
* 4777bb9 2015-03-19 keyfreq output is vcs friendly (Chen Bin)
* d486fb5 2015-03-18 better keyfreq (Chen Bin)
* 5a6990e 2015-03-17 better keyfreq (Chen Bin)
```

**Comment by CestDiego** [comment]
Add support for this plz

**Comment by CestDiego** [comment]
@dacap I think the point of this was to add the *exclude command* feature.

**Comment by dacap** [comment]
Oh, sorry @CestDiego, anyway as that one is more complex, I would prefer a pull request, would @redguardtoo like help with one?
