### ISSUE TITLE
Symbol's definition is void: reduce

### ISSUE THREAD

**Issue by mathias** [dacap/keyfreq#16]
When I run `keyfreq-show`, I get this on Emacs 24.5.1 (built from source) on my work laptop running OSX:

```
keyfreq-format-list: Symbol's function definition is void: reduce
```

When I run the same thing on my personal laptop, running Emacs 24.4.1 compiled from source, I don't get this error.

In both cases, I have `keyfreq-20141124.805` which appears to be the GitHub repo, but pulled from MELPA.

Google wasn't very helpful. Is it possible I'm missing some dependency?

Thanks in advance!

**Comment by dacap** [comment]
Hi @mathias, I think [this line](https://github.com/dacap/keyfreq/blob/master/keyfreq.el#L69) was introduced to fix that situation. I'm testing on Emacs 24.5 and keyfreq works. `cl-lib` is a built-in library, so you should have it.

Maybe Emacs is loading an older version of keyfreq. E.g. MELPA didn't update the compiled `.elc` file. Could you try to reinstall keyfreq?

**Comment by mathias** [comment]
I removed the MELPA-provided package and used the plain .el file from GitHub, with the same problem. I tried compiling Emacs from Git HEAD (https://savannah.gnu.org/git/?group=emacs) and still seeing it. It's very odd. I can run

```
(require 'cl-lib)
```

just fine. But running `keyfreq-show` still gives me the error about `reduce`.
