### ISSUE TITLE
Missing reduce? 

### ISSUE THREAD

**Issue by kowodo** [dacap/keyfreq#18]
When running keyfreq-show, I'm getting:

keyfreq-format-list: Symbol's function definition is void: reduce

[GNU Emacs 24.4.1 (x86_64-unknown-linux-gnu, GTK+ Version 3.10.8)]

**Comment by dacap** [comment]
Hi @kowodo, this problem was reported in #9 and #16 before, please check if [this solution](https://github.com/dacap/keyfreq/issues/9#issuecomment-50265304) works for you. I hope so.

**Comment by kowodo** [comment]
Yes that solves the problem for me. 

Thank you.

**Comment by shymega** [comment]
Hi - If this issue is resolved, can we close it?

**Comment by dacap** [comment]
@shymega it should be fixed with #19
